### ISSUE TITLE
Presel.__init__() missing 1 required positional argument: 'use_IB'

### ISSUE THREAD

**Issue by ben1628** [psemdel/py-trading-bot#17]
using

`http://127.0.0.1:8000/actualize_hist_paris/`

I got the above error, it seems it fails on /reporting/views.py

```
 presel=btP.Presel(symbols1=symbols,period1="1y",exchange="Paris")
TypeError: Presel.__init__() missing 1 required positional argument: 'use_IB'
ERROR:django.server:"GET /actualize_hist_paris/ HTTP/1.1" 500 69559
```

**Comment by psemdel** [comment]
Hum, I haven't used that one since a long time... I will fix that.

**Comment by psemdel** [comment]
Ok, I made the changes. There was already a test, but someone did not failed...

**Comment by ben1628** [comment]
Okay, I download the changes and now I get this

`
File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 204, in handle
    self.handle_one_request()
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 227, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/whitenoise/middleware.py", line 125, in __call__
    return self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/reporting/views.py", line 160, in actualize_hist_paris
    presel=btP.Presel(use_IB,actions1=actions,period1="1y",exchange="Paris")
  File "/home/usr/py-trading-bot/py-trading-bot/core/btP.py", line 73, in __init__
    st=StratPRD(use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/core/stratP.py", line 69, in __init__
    =retrieve_data(actions,period,use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 744, in retrieve_data
    cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 731, in retrieve_data_YF
    logger.error(e, stack_info=True, exc_info=True)
ERROR:django.request:Internal Server Error: /actualize_hist_paris/
Traceback (most recent call last):
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/reporting/views.py", line 160, in actualize_hist_paris
    presel=btP.Presel(use_IB,actions1=actions,period1="1y",exchange="Paris")
  File "/home/usr/py-trading-bot/py-trading-bot/core/btP.py", line 73, in __init__
    st=StratPRD(use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/core/stratP.py", line 69, in __init__
    =retrieve_data(actions,period,use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 744, in retrieve_data
    cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
TypeError: cannot unpack non-iterable NoneType object
'

**Comment by psemdel** [comment]
I suppose that you have no action with a stock exchange named "Paris"?

**Comment by ben1628** [comment]
Correct. I don't.

As as matter of fact, I only deal with Nasdaq and NYSE, so how do I fix the problem so I can see the report?

**Comment by psemdel** [comment]
Then you should not use the "actualize Paris", "actualize XETRA" buttons, the report 17h is also not needed. Only report 22h and actualize Nasdaq is necessary. Report 22h is what you should be using in normal time. I should write that somewhere...

**Comment by ben1628** [comment]
I still have trouble generating the Nasdaq reports:

First it complains about can only concatenate str (not list ) to str

at line 709 in orders/ib.py

so I try to fix it with this

            all_symbols=symbols
            all_symbols.append(index_symbol)

it allows me to go further, then it complains about 

TickerBase.history() got an unexpected keyword argument 'actions1'"

at line 717 ib.py

This is the dump:


  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 747, in retrieve_data
    cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 733, in retrieve_data_YF
    logger.error('Error in retrieve_data_YF', stack_info=True, exc_info=True)
e
TypeError("TickerBase.history() got an unexpected keyword argument 'actions1'")
ERROR:orders.ib:TickerBase.history() got an unexpected keyword argument 'actions1'
Traceback (most recent call last):
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 717, in retrieve_data_YF
    res=vbt.YFData.fetch(all_symbols, period=period,missing_index='drop',**kwargs)
  File "/home/usr/vectorbt.pro-main/vectorbtpro/data/base.py", line 838, in fetch
    raise e
  File "/home/usr/vectorbt.pro-main/vectorbtpro/data/base.py", line 835, in fetch
    out = cls.fetch_symbol(symbol, **_kwargs)
  File "/home/usr/vectorbt.pro-main/vectorbtpro/data/custom.py", line 1040, in fetch_symbol
    df = yf.Ticker(symbol).history(period=period, start=start, end=end, interval=timeframe, **history_kwargs)
TypeError: TickerBase.history() got an unexpected keyword argument 'actions1'
Stack (most recent call last):
  File "/home/usr/.vscode-server/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 1118, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 202, in handle
    self.handle_one_request()
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 227, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/whitenoise/middleware.py", line 125, in __call__
    return self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/reporting/views.py", line 174, in actualize_hist_nasdaq
    presel=btP.Presel(use_IB,actions1=actions,period1="1y",exchange="Nasdaq")
  File "/home/usr/py-trading-bot/py-trading-bot/core/btP.py", line 73, in __init__
    st=StratPRD(use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/core/stratP.py", line 69, in __init__
    =retrieve_data(actions,period,use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 747, in retrieve_data
    cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 734, in retrieve_data_YF
    logger.error(e, stack_info=True, exc_info=True)
ERROR:django.request:Internal Server Error: /actualize_hist_nasdaq/
Traceback (most recent call last):
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/usr/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/reporting/views.py", line 174, in actualize_hist_nasdaq
    presel=btP.Presel(use_IB,actions1=actions,period1="1y",exchange="Nasdaq")
  File "/home/usr/py-trading-bot/py-trading-bot/core/btP.py", line 73, in __init__
    st=StratPRD(use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/core/stratP.py", line 69, in __init__
    =retrieve_data(actions,period,use_IB,**kwargs)
  File "/home/usr/py-trading-bot/py-trading-bot/orders/ib.py", line 747, in retrieve_data
    cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
TypeError: cannot unpack non-iterable NoneType object
ERROR:django.server:"GET /actualize_hist_nasdaq/ HTTP/1.1" 500 85240

**Comment by ben1628** [comment]
I just don't know whether I run the program correctly.  I didn't set anything up in Admin, I use use the same dump data, and click actualize_hist_nasdaq.

**Comment by psemdel** [comment]
First on the present version:
retrieve_data(self.actions,self.period,use_IB )
So no kwargs, the action1 cannot reach retrieve_data_YF

Concerning the concatenate
all_symbols=symbols+[index_symbol]

So it should both be lists.

I will recreate a dump, it must be outdated...

**Comment by ben1628** [comment]
Oh, Ic.

Thanks for clarify what's going on.  Looking forward to your new dump.

As for the concatenation, I will try it again.  tbh, I am still finding my way around, but I think I am getting there.

**Comment by ben1628** [comment]
I have updated to the current version and recreate the data from dump. However still 
I'm still getting the error keyword action1

Here is the stack trace:

```
ERROR:django.request:Internal Server Error: /actualize_hist_nasdaq/
Traceback (most recent call last):
  File "/home/benson/.vbt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/benson/.vbt/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benson/py-trading-bot/py-trading-bot/reporting/views.py", line 174, in actualize_hist_nasdaq
    presel=btP.Presel(use_IB,actions1=actions,period1="1y",exchange="Nasdaq")
  File "/home/benson/py-trading-bot/py-trading-bot/core/btP.py", line 73, in __init__
    st=StratPRD(use_IB,**kwargs)
  File "/home/benson/py-trading-bot/py-trading-bot/core/stratP.py", line 69, in __init__
    =retrieve_data(actions,period,use_IB,**kwargs)
  File "/home/benson/py-trading-bot/py-trading-bot/orders/ib.py", line 747, in retrieve_data
    cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
TypeError: cannot unpack non-iterable NoneType object
ERROR:django.server:"GET /actualize_hist_nasdaq/ HTTP/1.1" 500 85289
```
1/ on line 9 of StratP.py, it has

`retrieve_data(actions,period,use_IB,**kwargs)
`
so it has kwargs

2/ on line 747, it is calling

if not use_IB:

`            cours, symbols, index_symbol=retrieve_data_YF(actions,period,**kwargs)
`

**Comment by psemdel** [comment]
I did not look in StratP but in btP. I correct that... (I use mainly st=st )

**Comment by ben1628** [comment]
Can you also fix the backports.zoneinfo problem in orders/Models.py and testorders.py. I know you did that in reporting/telegram.py which is great.

Thanks
