### ISSUE TITLE
py-trading-bot discord for discussion 

### ISSUE THREAD

**Issue by 786449611** [psemdel/py-trading-bot#43]
hi, I am a vectorbtpro user but could hardly find a good one for live-trading. Your work saved me, thanks for sharing!  But unluckily i have not got it work yet. I want a place to discuss with guys who use py-trading-bot, and I think many others also want too, 

Is it OK for you to create a discord server to communicate? or use the one I created below?

**[py-trading-bot]
https://discord.gg/emfCWD7hrr**

Thank you!

**Comment by Fun1628** [comment]
He is doing a fantastic job.  Read all the md under Doc to understand the process.

**Comment by 786449611** [comment]
hi, thanks, 
i am now stuck in installing IB gateway in wsl2. 
searched some materials but not worked as expected, how did you make it?

**Comment by Fun1628** [comment]
Read some of the closed issues

**Comment by psemdel** [comment]
Hi, sorry that I am really not so reactive... I have no problem that you make a discord, but presently I can really not promess to be online and I fear it will be a while until I am available again. 
There surely are many things to be improved. I am not a professional coder.
Installing IB gateway, so it is not related to this bot I would say right? Or is the problem the communication between the bot and the running gateway?

**Comment by 786449611** [comment]
hi, I have successfully installed IB gateway in Ubuntu. refering this link.
https://medium.com/@FMZQuant/instructions-for-installing-interactive-brokers-ib-gateway-in-linux-bash-feca03350844

by Got error after  ./start_bot.sh in WSL2 ubuntu terminial (Win11)
it says ModuleNotFoundError: No module named 'telegram'
(since there is no telegram.py file there.)

and then browser opened http://localhost:8000/start_bot
showing "Unable to connect".

In my settings, i have used simple database as the guides says.  PostgresQL is not installed/set.
![image](https://github.com/user-attachments/assets/16e076f6-4dec-4d05-835c-a1eb9742f00c)
here is my setting file:[settings.txt](https://github.com/user-attachments/files/16478341/settings.txt)

and, my IBgateway port  is 4002 shown in IB, not 4001.
Could you check where is the problem is? Thank you very much!
---
log details:
[2024-08-03 06:00:12] INFO 668 Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/wiki/.local/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/wiki/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/wiki/.local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/wiki/py-trading-bot/py-trading-bot/orders/apps.py", line 11, in ready
    from reporting.views import create_ss_sub
  File "/home/wiki/py-trading-bot/py-trading-bot/reporting/views.py", line 3, in <module>
    from reporting.telegram import start, cleaning_sub
  File "/home/wiki/py-trading-bot/py-trading-bot/reporting/telegram.py", line 29, in <module>
    from telegram.ext import CommandHandler
**ModuleNotFoundError: No module named 'telegram'**

**Comment by psemdel** [comment]
telegram not found is because you did not install python-telegram-bot, which is normally included in vbtpro.

my IBgateway port is 4002 shown in IB, not 4001.-> set the right one in the bot in settings. Maybe it was a mistake from my side, who knows?

**Comment by 786449611** [comment]
Hi, thank you, i installed python-telegram-bot mannualy and start again . New errors... do i need to restart?

1.6379: bind: Address already in use
2. sudo apt install tightvncserver# Generated by Django 5.0.6 on 2024-07-06 03:41
SyntaxError: invalid syntax


wiki@LegionPC:~/py-trading-bot/py-trading-bot$ ./start_bot.sh
221073:C 03 Aug 2024 17:17:34.228 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
221073:C 03 Aug 2024 17:17:34.228 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=221073, just started
221073:C 03 Aug 2024 17:17:34.228 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
221073:M 03 Aug 2024 17:17:34.228 * Increased maximum number of open files to 10032 (it was originally set to 1024).
221073:M 03 Aug 2024 17:17:34.228 # **Could not create server TCP listening socket *:6379: bind: Address already in use**
[2024-08-03 09:17:34] INFO 148 Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-08-03 09:17:34] INFO 160 NumExpr defaulting to 8 threads.
/home/wiki/.local/lib/python3.10/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
[2024-08-03 09:17:36] INFO 148 Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-08-03 09:17:36] INFO 160 NumExpr defaulting to 8 threads.
/home/wiki/.local/lib/python3.10/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
Watching for file changes with StatReloader
[2024-08-03 09:17:38] INFO 668 Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
    self.check_migrations()
  File "/home/wiki/.local/lib/python3.10/site-packages/django/core/management/base.py", line 581, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/wiki/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/wiki/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/wiki/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 229, in build_graph
    self.load_disk()
  File "/home/wiki/.local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 120, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wiki/py-trading-bot/py-trading-bot/orders/migrations/0001_initial.py", line 1
    sudo apt install tightvncserver# Generated by Django 5.0.6 on 2024-07-06 03:41
         ^^^
**SyntaxError: invalid syntax**

**Comment by psemdel** [comment]
Error: That port is already in use. 

Means that you have already the bot / django running.

**Comment by psemdel** [comment]
> Hi, thank you, i installed python-telegram-bot mannualy and start again . New errors... do i need to restart?
> 
> 1.6379: bind: Address already in use
> 2. sudo apt install tightvncserver# Generated by Django 5.0.6 on 2024-07-06 03:41
> SyntaxError: invalid syntax
This part, I did not understand. What did you comment out?

**Comment by 786449611** [comment]
![image](https://github.com/user-attachments/assets/5468eddf-e157-4935-9d37-edcad91249a5)
this! 
because if not, it will generate SyntaxError: invalid syntax at [apt]

**Comment by ben1628** [comment]
You are jumping too quickly, you need to make sure your telegram is working first

That means you have to talk to bot father and setup your telegram bot.
Google on how to!

1. Go to test telegram to make sure you get a response from your own telegram bot

2. Use test ib to make sure you are communicating with IB

3. Read the installation guide, the documents under doc folder

It's a powerful bot which requires some effort to set it up properly

**Comment by ben1628** [comment]
If everything is working you will see something similar to bot interface1.png after do http to startbot

**Comment by psemdel** [comment]
The file of the migration is generated by django when you made the first migration. It is not coming from my repo.

About IB, you should start it before the bot (but it will work also if you do it afterwards, there is a fallback on YF).

You can create a report to test.
